- name: demo on data types
  hosts: local
  connection: local
  vars:
    PROGRAM: "Devops with AWS"
    DURATION: "140 HRS"
    IS_LIVE: true 
    DETAILS:  "Sivakumar Reddy"
    MONTHS: 4
    TRAINER: "Sivakumar Reddy"
    TOPICES:
     - Linux
     - Shell
     - Ansible
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg:
          Program {{ PROGRAM }}
          Duration {{ DURATION }}
          Is_Live {{ IS_LIVE }}
          Details {{ Details }}
          Topices {{ TOPICES }}
