- name: demo or conditions
  hosts: local
  connection: local
  vars:
   IS_LIVE: true
  tasks: 
  - name: check Live or not 
    ansible.builtin.debug:
      msg: "yes it is Live"
    when: IS_LIVE  